runs-on: ubuntu-latest

steps:
  - name: Checkout do código
    uses: actions/checkout@v2

  - name: Configurar Node.js
    uses: actions/setup-node@v2
    with:
      node-version: '14'

  - name: Instalar dependências
    run: |
      echo "Instalando dependências..."
      npm install

  - name: Executar testes com Node.js e módulos ESM
    run: |
      echo "Executando testes com Node.js e módulos ESM..."
      npx mocha --experimental-specifier-resolution=node --loader esm teste.spec.mjs