name: Mostrar informações de commit e executar testes

on:
  push:
    branches:
      - main  

jobs:
  show-commit-info:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # ou a versão do Node.js que você está usando

      - name: Instalar dependências
        run: npm install

      - name: Executar testes
        run: npm test

      - name: Mostrar informações de commit
        run: echo "Commit feito por ${{ github.actor }} em ${{ github.repository }}/${{ github.sha }}"
